version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: highlander
      POSTGRES_PORT: 5431
